- io.ts
- redis_test.ts
> Repair errors in using Unicode coded characters

- .travis.yml
- README.md
- io.ts
- pipeline.ts
- pipeline_test.ts
- pubsub.ts
- pubsub_test.ts
- redis.ts
- redis_test.ts
- test.ts
Deno 0.11 started breaking builds, I've updated std to latest version to make it work again.
> bump: deno_std v0.12.0

- .circleci/config.yml
- README.md
> ci: Use CircleCI

- io.ts
- modules-lock.json
- modules.json
- vendor/https/deno.land/std/fmt/colors.ts
- vendor/https/deno.land/std/io/bufio.ts
- vendor/https/deno.land/std/testing/asserts.ts
- vendor/https/deno.land/std/testing/mod.ts
- vendor/https/deno.land/std/util/async.ts
I updated the module versions and fixed https://github.com/keroxp/deno-redis/issues/25
Could you review it? 😄
> fix: #25 fix readline issue

- redis.ts
- redis_test.ts
Related to: https://github.com/keroxp/deno-redis/issues/30
The key prefix option is a little bit complicated, I will send a small one first.
> feat: add db option and remove a deprecated option 

- redis.ts
> Check bulk reply type strictly

- io.ts
- pipeline.ts
- pipeline_test.ts
- redis.ts
- redis_test.ts
- Improved type assertion for replies.
- Fixed reply type of some commands
> Improve type checking

- io.ts
- pipeline.ts
- redis.ts
- redis_test.ts
- tests/connection_test.ts
- tests/geo_test.ts
- tests/hash_test.ts
- tests/hyper_loglog_test.ts
- tests/list_test.ts
- tests/set_test.ts
- tests/test_util.ts
- Add tests for `hash` `hll` ` list` `set`
- Fixed some commands
> Fixing 20200308

- command.ts
- redis.ts
- tests/geo_test.ts
- tests/string_test.ts
> fix: bitfield

- .github/workflows/build.yml
- pubsub_test.ts
> build: run CI for all PRs

- connection.ts
> fix(#106): fix the naming collision between redis.ts and connection.ts

- command.ts
- redis.ts
- tests/string_test.ts
Fixes #101 
Let me know if I didn't follow convention somewhere. I'll be happy to change it!
> Add STRALGO command

- README.md
This PR updates old urls to new ones in README.md.
> docs(README): update links

- stream.ts
- tests/stream_test.ts
> BREAKING: Change return type of the streams API to Record

- command.ts
- redis.ts
- tests/list_test.ts
> feat: Implement LPOS command

- command.ts
- redis.ts
- tests/connection_test.ts
> feat: Implement CLIENT ID command

- io.ts
> docs: Add more JSDoc comments to io.ts

- README.md
> docs: Update usage of stream commands

- command.ts
- redis.ts
- tests/connection_test.ts
> feat: Implement CLIENT SETNAME & GETNAME

- README.md
At the PR #176, I mistakenly updated the documentation... :confounded:
> docs: Update usage of stream commands (part 2)

- command.ts
- redis.ts
- tests/connection_test.ts
Part of #174.
Hello :wave: My first contribution! Please let me know if it can be improved. Thanks!
> feat: Implement CLIENT PAUSE

- command.ts
> docs: Add JSDoc comments to RedisCommands.hset

- command.ts
- mod.ts
- redis.ts
- tests/connection_test.ts
> feat: Implement CLIENT TRACKING

- command.ts
- redis.ts
- tests/connection_test.ts
> feat: Implement CLIENT GETREDIR

- command.ts
- redis.ts
- tests/connection_test.ts
> feat: Implement CLIENT INFO

- command.ts
- redis.ts
- tests/client_test.ts
> feat: Implement CLIENT TRACKINGINFO

- command.ts
- mod.ts
- protocol/mod.ts
- protocol/types.ts
- redis.ts
- tests/executor_test.ts
- tests/key_test.ts
Currently, the combination of dump and restore is not working. In order to make them work correctly, their signatures have been changed in this PR.
> BREAKING: Fix signature of dump and restore

- modules-lock.json
- modules.json
- vendor/https/deno.land/std/fmt/colors.ts
This file is no longer used. :thinking:
> chore: Remove std/fmt/colors

- tests/cluster/test.ts
> test: Add a test for too many redirections

- .github/workflows/build.yml
- README.md
- command.ts
- import_map.test.json
- redis.ts
> ci: Run 'deno test --doc'

- README.md
- redis.ts
- tests/general_test.ts
> feat: Redis#sendCommand

- executor.ts
- experimental/cluster/mod.ts
- mod.ts
- pipeline.ts
- protocol/command.ts
- protocol/mod.ts
- redis.ts
This reverts commit 2ca4fc29c04b284f7391a1bb15110385a815f925.
> BREAKING: Revert "refactor: Add CommandExecutor#batch (#254)"

- tests/cluster/test_util.ts
> fix(#273): Add delay before starting experimental/cluster tests

- redis.ts
- tests/commands/sorted_set.ts
> fix(#284): `zadd` with `opts` argument does not work

- redis.ts
- tests/commands/sorted_set.ts
> fix(#286): `zaddIncr` does not work

- README.md
- backoff.ts
- connection.ts
- mod.ts
- tests/backoff_test.ts
- tests/commands/general.ts
- tests/commands/pubsub.ts
Closes #160
- Implemented retry mechanism with exponential backoff algorithm
- Removed `RedisConnectionOptions.retryInterval`
- Added `RedisConnectionOptions.backoff`
> BREAKING: Improve retry mechanism

- command.ts
- redis.ts
- tests/commands/geo.ts
> fix: Improve type definition of `geopos`

- protocol/reply.ts
- protocol/types.ts
- redis.ts
- stream.ts
- tests/commands/general.ts
- tests/commands/geo.ts
- tests/commands/hash.ts
- tests/commands/key.ts
- tests/commands/list.ts
- tests/commands/sorted_set.ts
- tests/commands/string.ts
> BREAKING: Change `BulkNil` from `undefined` to `null`

- command.ts
- redis.ts
- tests/commands/string.ts
> feat(stralgo): improve type definition

- redis.ts
- tests/commands/pubsub.ts
Hi! Just a minor typo I think.
Reference: https://redis.io/commands/pubsub-numsub/
> fix: fix NUMSUB command

- protocol/command.ts
- tests/commands/general.ts
**this branch:**
```
┌───────┬──────────────────┬───────┬────────┬─────────────────────────┬────────────────────────┬─────────────────────────┬─────────────────────────┬─────────┐
│ (idx) │ name             │ ops   │ margin │ min                     │ max                    │ mean                    │ median                  │ samples │
├───────┼──────────────────┼───────┼────────┼─────────────────────────┼────────────────────────┼─────────────────────────┼─────────────────────────┼─────────┤
│     0 │ "ping"           │ 17103 │   2.38 │ 0.000050778605280974946 │ 0.00008504098360655738 │ 0.000058470835821568045 │ 0.000056866648221940366 │      58 │
│     1 │ "set & get"      │  8731 │   2.01 │    0.000099601593625498 │  0.0001501597444089457 │  0.00011453520751749205 │ …
```
> perf(protocol/command): optimize `writeCommand`

- protocol/reply.ts
- pubsub.ts
- tests/commands/pubsub.ts
> feat: PubSub with binary messages

- tests/commands/key.ts
> test: `SORT` with multiple patterns

- .github/workflows/build.yml
- deno.json
- modules-lock.json
- modules.json
- tools/make_mod.ts
- vendor/https/deno.land/std/streams/write_all.ts
> ci: re-enable `deno task make_mod`

- deno.json
- experimental/cluster/mod.ts
- modules-lock.json
- modules.json
- tests/cluster/test.ts
- vendor/https/cdn.skypack.dev/cluster-key-slot/lib/index.js
- vendor/https/cdn.skypack.dev/lodash-es/sample.js
- vendor/https/cdn.skypack.dev/lodash-es/shuffle.js
- vendor/https/cdn.skypack.dev/lodash-es/uniqBy.js
- vendor/https/esm.sh/cluster-key-slot/lib/index.js
- vendor/https/esm.sh/lodash-es/sample.js
- vendor/https/esm.sh/lodash-es/shuffle.js
- vendor/https/esm.sh/lodash-es/uniqBy.js
> chore: import `lodash-es` and `cluster-key-slot` from esm.sh

- .github/workflows/build.yml
- deno.json
- deno.lock
> ci: add `deno.lock`, run tests with `--frozen-lockfile`

- command.ts
- deps/std/testing.ts
- redis.ts
- tests/commands/string.ts
> feat: support `GET` option of the SET command

- deno.lock
- deps/lodash-es.js
- deps/std/collections.ts
- deps/std/random.ts
- experimental/cluster/mod.ts
- tests/cluster/test.ts
> deps: migrate `lodash-es` to `@std/{collections,random}`

- deno.json
> chore: change the package name to `@db/redis`

- README.md
> docs(README): `deno-redis` should be imported from JSR

- protocol/deno_streams/reply.ts
Support *long* lines printed by redis (e.g. a big hash value) by reading the entire line (all chunks available) instead of the first chunk.
> fix: support long lines

- .github/workflows/build.yml
- .github/workflows/publish.yml
> deps(ci): pin `denoland/setup-deno`

- command.ts
- connection.ts
- internal/symbols.ts
- protocol/deno_streams/reply.ts
- protocol/shared/reply.ts
- protocol/shared/types.ts
- protocol/web_streams/reply.ts
- protocol/web_streams/reply_test.ts
- tests/commands/resp3.ts
- tests/commands_test.ts
> feat(RESP3): support map replies
