redis.ts
redis_test.ts

`Redis.spop()` returns an array when the `count` argument is passed in.
So I modified the signature of it.
```typescript
const redis = await connect({ hostname: 'localhost', port: 6379 });
const key = 'myset';
await redis.sadd(key, 'a', 'b', 'c');
console.info(await redis.spop(key)); // -> c
```
```typescript
const redis = await connect({ hostname: 'localhost', port: 6379 });
const key = 'myset';
await redis.sadd(key, 'a', 'b', 'c');
console.info(await redis.spop(key, 2)); // -> [ "a", "b" ]
```

fix: improve signature of spop

---

redis.ts
redis_test.ts

`Redis.zrange()` does not work when used with `withScore` option.
This PR fixes this problem.
```typescript
const redis = await connect({ hostname: 'localhost', port: 6379 });
await redis.zadd('myzset', 1, 'one');
await redis.zrange('myzset', 0, -1, { withScore: true });
```
```
error: Uncaught Error: -ERR syntax error
► io.ts:149:11
149     throw new ErrorReplyError(line);
^
at ErrorReplyError (errors.ts:5:7)
at tryParseErrorReply (io.ts:149:11)
at readReply (io.ts:65:7)
```

fix: zrange with 'withScore' option

---

redis.ts
redis_test.ts
tests/string_test.ts
tests/test_util.ts

- Added tests for string commands.
- Fixed `getrange` because to avoid the following warning:
- `wrong type definition for status: GETRANGE bulk world`
- Fixed `incrbyfloat` because to avoid the following warning:
- `wrong type definition for status: INCRBYFLOAT bulk 2.6`
- Noticed that `bitfield` is not completely implemented yet.
- I'll open an issue about this.

added: string_test.ts

---

redis.ts
tests/general_test.ts

This PR resolves #81.
Please review @keroxp 🙏, cc @devalexqt.
- Added the `password` property to `RedisConnectOptions`.
- `AUTH` command is now executed automatically when password is specified.

feat: password authentication

---

pubsub.ts
pubsub_test.ts

fix(#89): subscriber shouldn't throw BadResource error when connection is closed

---

command.ts
redis.ts
redis_test.ts
tests/acl_cmd_test.ts

Use @Terkwood's #86 as request template.
Adds support for Redis Server commands.
This change set will resolve #35 . 🚢
Author will run each command and verify that argument names match the canonical names exposed by Redis. Minimal command form should be included in EACH doc string. Author will check each TS return type to make sure it matches server return type (Ideally these are encoded in the test). This isn't ideal since only exports trigger deno doc, but we want to have these methods documented nonetheless.

🚧 Implement new server commands from Redis 6 🚧

---

pubsub.ts

I think this is a mistake; `psubscribe` refers to `this.channels` and `punsubscribe` refers to `this.patterns`...

Fix bad reference to property `channels`

---

README.md
command.ts
connection.ts
io.ts
pipeline.ts
pubsub.ts
pubsub_test.ts
redis.ts
tests/connection_test.ts

Add a test for an issue that was reported where the process exits if the connection to the Redis server is lost while being subscribed to a topic.
To run this test, you will need to specifically allow to run (execute) commands and enable the unstable API -- `deno test --allow-net --allow-run --unstable`
Reference: https://github.com/keroxp/deno-redis/issues/83

Implement retriable connection

---

.github/workflows/build.yml
.gitignore
Makefile
pubsub_test.ts
tests/test_util.ts

ci: use locally-installed redis instead of dockerized one

---

connection.ts
errors.ts
io.ts
pubsub_test.ts

Closes #104.
EOF is thrown when a recently closed connection allows message to pass through but response coming back is EOF. I'm not sure why `ConnectionRefused` or `ConnectionReset` is not thrown before the message is sent, but this patch adds check for EOFError to performs necessary reconnect attempt and eventually set `_isConnected = false`.

fix(#104): fix testSubscribe4

---

tests/connection_test.ts

The tests for `Redis.executor` already exist in [`tests/general_test.ts`](https://github.com/denolib/deno-redis/blob/47d09695224bcc9aa662a9cdb260b18cf4e28c34/tests/general_test.ts#).

chore: remove an unnecessary test for Redis.executor

---

command.ts
redis.ts
tests/general_test.ts
tests/geo_test.ts
tests/hash_test.ts
tests/key_test.ts
tests/list_test.ts
tests/pipeline_test.ts
tests/sorted_set_test.ts
tests/string_test.ts

This PR aims to improve the commands API to better conform with the actual Redis API and improve developer experience.
-  `migrate`: add `auth` option
-  `object_idletime`: rename the function
-  `object_freq`: add `BulkNil` to return type
-  `restore`: add `absttl`, `idletime`, and `freq` options
-  `scan`: add `type` options
-  `sort`: make `limit` option an object and make `order` optional
-  `incrbyfloat`: return type `BulkString`
-  `mset`: use Record to add multiple entries
-  `msetnx`, `geoadd`, `hmset`, and `hset`: ditto
-  `set`: add `keepttl` option
-  `geopos`: return type `BulkString`
-  `geo*` : adjust options names
-  `bzop*`: make `timeout` first argument to use rest with `keys`
-  `z*store`: use Record to add multiple arguments
-  `eval`: remove `numkeys` argument, get …

chore: improve commands API correctness

---

.github/workflows/build.yml

See https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

ci: use GITHUB_ENV instead of set-env

---

redis.ts
tests/connection_test.ts
tests/general_test.ts

Resolves #153 
This adds a helper function to `redis.ts` (I think it's the right place? I don't really see any file for helpers and `connection.ts` seems to be more focused on internal operation of connecting to redis). It takes a redis URL and parses it according to IANA assignments for [`redis`](https://www.iana.org/assignments/uri-schemes/prov/redis) and [`rediss`](https://www.iana.org/assignments/uri-schemes/prov/rediss) schemes.
Things I'm not certain of here:
- location of the function. As mentioned, I'm not sure if `redis.ts` is the right place for it
- tests and their location. I put them in `connection_test.ts`, but I don't know if they should stay there or go to `general_test.ts`. Also, originally I wanted there to be a test with a connection to server, but for some reason …

resolve #153 - add parseURL function

---

command.ts
connection.ts
pipeline.ts
pubsub.ts
redis.ts

This PR is intended to make the output of `deno doc` move visible:
**Before this fix:**
```shell
$ deno doc mod.ts RedisCommands
Defined in file:///home/uki00a/ghq/github.com/uki00a/redis/command.ts:39:0 
type RedisCommands = { auth(password: string): Promise<Status>; auth(username: string, password: string): Promise<Status>; ... tx(): RedisPipeline; pipeline(): RedisPipeline; }
```
**After this fix:**
```shell
$ deno doc mod.ts RedisCommands
Defined in file:///home/uki00a/ghq/github.com/uki00a/redis/command.ts:39:0 
interface RedisCommands
auth(password: string): Promise<Status>
auth(username: string, password: string): Promise<Status>
...
xack(key: string, group: string, ...xids: XIdInput[]): Promise<Integer>
The XACK command removes one or multiple messages 
from the pending entries …
```

chore: Use interface instead of type

---

tests/stream_test.ts

Trying to see how the Github Actions runs behave with these new `delay` values.
This will hopefully resolve #164

Use a less collision-prone stream name in stream tests

---

command.ts
mod.ts
redis.ts
tests/connection_test.ts
tests/test_util.ts

Part of #174.
Hello 👋 . Two changes in this PR:
1. Implement `afterEach` in the test suite and added creating the client connection to a `beforeEach` in `connection_test` and `client.close()` to `afterEach`. I think some of the effects of client tracking were affecting some of the tests in client caching.
2. Implement client caching
If you like 1. would it be better to do it in a separate PR?

feat: Implement CLIENT CACHING

---

README.md
command.ts
pubsub.ts
redis.ts

In some situations, a Pub/Sub subscriber receives messages in an array format. The current type definitions do not support those situations, so this commit changes `subscribe` and `psubscribe` to generic methods.

fix: Make `subscribe` and `psubscribe` methods generic

---

command.ts
mod.ts
redis.ts
tests/connection_test.ts

feat: Implement CLIENT UNBLOCK

---

command.ts
redis.ts
tests/connection_test.ts

Part of #174. Sorry, a lot of these PRs recently, but it's quite fun 😄 Thanks for all the reviews until now @uki00a!
By the way the docs say
> Since Redis 6.2, the recommended mode for client pause is WRITE. This mode will stop all replication traffic, can be aborted with the CLIENT UNPAUSE command.
and as far as I can tell the unpause command only works on clients paused using WRITE mode. I wonder if it is worth adding some documentation?

feat: Implement CLIENT UNPAUSE

---

command.ts
mod.ts
redis.ts
tests/client_test.ts

feat: Implement CLIENT LIST

---

pipeline.ts
redis.ts

I think `Redis.connection` should be used only internally. In this PR, it is removed in preparation for the v1 release.

BREAKING: Remove Redis.connection

---

tests/client_test.ts
tests/cluster/test.ts
tests/general_test.ts
tests/pubsub_test.ts
tests/stream_test.ts

`assertThrowsAsync` has been deprecated in deno_std v0.104.0.

chore: Replace assertThrowsAsync with assertRejects

---

README.md

The documentation for Cluster support detailed setting up a Redis cluster, but not consuming one (which requires using the experimental cluster executor).
This PR adds documentation on how to consume a Redis Cluster to the README

docs(cluster): improve clustering example in README

---

pubsub.ts
tests/commands/pubsub.ts

This change is intended to improve consistency with `Deno.Conn` and `Redis`

BREAKING: Change `RedisSubscription#close()` to return `void`

---

connection.ts

Fixes issue #300
You can now use redis client with cloud hosted redis (redis enterprise/cloud stack) or any other redis server that has user+password authentication.
PR is not breaking, but has changed RedisConnectionOptions to support an optional username: string property.
Tests not included since, only tests that make sense require a redis instances setting up with:
- password only (auth token only)
- username + password
- no auth
I did not see mock redis server for this in tests, and existing test for authentication is only checking if a parameter has been passed and is valid.  Which exception handling catches anyway.
ps. been a while since I did a PR.  (also note, I have this code in production, be nice to use official repo for this. )

added username+password auth support

---

command.ts
mod.ts
redis.ts
tests/commands/sorted_set.ts

Hi there,
This PR adds the [zinter](https://redis.io/commands/zinter/) command which was missing. I tried to follow the same patterns I saw used for the other commands. Fun fact I learned today - `sinter` also works with sorted sets, but there's not `WITHSCORES` options which is what I needed. 
Cheers

feat: add zinter command

---

stream.ts
tests/commands/stream.ts

Partially address #333. I believe global fix would be to correct the types. Deno fmt 1.25.3 has been run on the files.

fix xread timeout

---

redis.ts

We are currently creating a lazy client and would like a way to force a connection during server initialization.
We can send a dummy request to do this, but since there's already a `close()` method, adding `connect()` and being explicit is a lot nicer.
Let me know if this is something you're interested in adding. Thank you!

Expose connect method on Redis

---

redis.ts

gm deno's,
i noticed that calling `sort` with multiple patterns caused `[uncaught application error]: Error - -ERR syntax error` and fixed it in this pr.
issue:
```typescript
{ // SortOpts
by: `*->foo`,
patterns: ["*->bar", "*->zed"],
}
```
yielded `GET *->bar *->zed` because:
```typescript
args.push("GET", ...opts.patterns)
```
solution:
```typescript
args.push(...opts.patterns.flatMap((pattern) => (["GET", pattern])))
```
to correctly yield `GET *->bar GET *->zed`

fix multi-pattern sorts

---

stream.ts

xid can be user-generated via xadd command.
https://redis.io/commands/xadd/

Expand XIdInput to string

---

connection.ts
executor.ts
redis.ts

This change is needed for #368

refactor: move command queue from `MuxExecutor` to `RedisConnection`

---

connection.ts
internal/symbols.ts
pipeline.ts
protocol/command.ts
protocol/mod.ts
pubsub.ts

`std/io` has been deprecated in [v0.203.0](https://github.com/denoland/deno_std/releases/tag/0.203.0). This PR removes `reader` and `writer` from `Connection` to remove the dependency on `std/io`.

BREAKING: remove `reader` and `writer` from `Connection`

---

connection.ts
internal/symbols.ts
protocol/deno_streams/command.ts
protocol/deno_streams/mod.ts
protocol/shared/protocol.ts
protocol/web_streams/command.ts
protocol/web_streams/mod.ts
pubsub.ts
redis.ts
tests/commands/pubsub.ts

fix: don't hang on multiple `subscribe()` calls

---

connection.ts
tests/commands/pipeline.ts

This PR fixes mixed response problem for parallel pipeline calls.
I made the modification so as the pipeline calls queued in the same way as regular commands.
To achieve this, the type of command queue item has changed to hold a general lambda function.
In my previous branch (yahiro07:pipeline-parallel-execution), there is a problem it doesn't work with Redis 6.
In this branch (yahiro07:pipeline-parallel-execution-2), I confirmed it works with both Redis 6 and  Redis 7. 
Please check:
- The test fails if you only add the test code.
- The test passes if you apply whole changes.
Closes #427

fix: fix concurrent pipeline invocation results

---

connection.ts
tests/reconnect_test.ts

This PR will fix the hangup problem in auto-reconnect.
I added a flag in `sendCommand` options.
The flag `inline` bypasses the queueing and executes the command immediately.
Hangup problem is avoided by executing the command `AUTH` and `SELECT` with `inline` options.
Please check:
- The fails (hangs up) if you only add the test code.
- The test passes if you apply whole changes.
Closes #430

Fix auto reconnect hangup

---

redis.ts

This PR fixes quite an obvious bug (an unexpected behavior) in case an argument passed is 0.
The `0` itself is a valid value for the affected arguments `COUNT` and, most importantly, `BLOCK`.
- `COUNT 0` should return an empty list ([source](https://redis.io/docs/latest/commands/lpos/#:~:text=LPOS%20mylist%20c-,COUNT%200,-%5B2%2C6%2C7%5D))
- `BLOCK 0` means to never timeout ([source](https://redis.io/docs/latest/develop/data-types/streams/#listening-for-new-items-with-xread:~:text=BLOCK%20option%20with%20a%20timeout%20of%200%20milliseconds%20(that%20means%20to%20never%20timeout)))
However, these arguments are currently omitted entirely when their value is 0.
This is caused by checking the argument values for being [truthy](https://developer.mozilla.org/en-US/docs/Glossary/Truthy) that 0 …

fix: do not omit args if value is 0

---

redis.ts
stream.ts

A range that can be used in `XPENDING` is defined the same way as in `XRANGE`.
Currently, when calling `xpendingCount` the `start` and `end` arguments have `number | "-"` type, which prevents users from specifying other valid forms of `XIdInput` and indicates that the method cannot process an `XId` object.
- Update type definitions of `start` and `end` to `XIdNeg` and `XIdPos` accordingly, just like it's done for `xrange`.
- Wrap `start` and `end` arguments with `xidstr` that would transform a valid `xIdInput` to string ID.

fix: use proper xid types for xpending range

---

command.ts
mod.ts
redis.ts
tests/commands/sorted_set.ts

~Introduces a small breaking change to the type definition of `Redis#zadd`.~

feat: add `nx` and `xx` options to `ZAddOpts`

---

deno.lock
deps/std/assert.ts
deps/std/async.ts
deps/std/bytes.ts
deps/std/testing.ts

- Bumps `@std/assert` to `1.0.7`
- Bumps `@std/async` to `1.0.8`
- Bumps `@std/bytes` to `1.0.3`
- Bumps `@std/testing` to `1.0.4`

deps: upgrade `@std/{assert,async,bytes,testing}`

---

.github/workflows/build.yml
deno.json
pipeline.ts
protocol/deno_streams/command.ts
protocol/deno_streams/mod.ts
protocol/deno_streams/reply.ts
protocol/shared/types.ts
protocol/web_streams/mod.ts
redis.ts
tests/commands/pipeline.ts
tests/commands/stream.ts
tests/test_util.ts

ci: run `deno publish --dry-run`

---

.github/workflows/publish.yml

ci: add `.github/workflows/publish.yml` to publish `deno-redis` to JSR

---

connection.ts

Just added a simple caCerts options to allow connecting to TLS enabled servers with self-signed ca. This closes #469

add self-signed root ca support for tls (fixes #469)

---

connection.ts

feat: always use TLS if  is specified

---

connection.ts
mod.ts
redis.ts
tests/commands/connection.ts
tests/commands_test.ts

Tried to imitate node-redis event listener to make migrations easier. Having an event handler is always useful for logging, debugging and tracing as well.
**connect**: fires when (re)connected sucessfully
**ready**: fires when (re)connected and authenticated sucessfully, and ready to send commands
**reconnecting**: fires only before reconnection with a delay
**close**: fires after connection is closed for whatever reason
**end**: fires after connection is closed and terminated, no reconnection is planned
**error**: fires when an unexpected/uncontrolled error occurs

add connection event listener support similar to node-redis

---

connection.ts
events.ts
mod.ts
redis.ts
tests/commands/connection.ts

Follows-up to #475. Type definitions have been improved so that type errors are caused for unsupported events.

feat: improve type-safety for events

---

connection.ts
deno.json
executor.ts
experimental/pool/mod.ts
pool/default_pool.ts
pool/default_pool_test.ts
pool/executor.ts
pool/mod.ts
pool/pool.ts
redis.ts
tests/pool_test.ts

feat: basic infrastructure for connection pooling

---

README.md
connection.ts
tests/commands/connection.ts

feat: `AbortSignal` support for `connect()`
